#!/bin/bash
# gen-review-package.sh — 预生成 Review Package（Superpowers 6.0 优化）
#
# 用法: bash gen-review-package.sh <项目目录> [base_ref] [head_ref]
#
# 生成 review-package.md 文件，包含：
#   - commit list
#   - files changed summary
#   - net diff with context
#
# tester 只读此文件，不跑 git 命令 → -10% token
#
# 如果未指定 base_ref/head_ref，自动检测最近一次提交

set -euo pipefail

PROJECT_DIR="${1:-.}"
BASE_REF="${2:-}"
HEAD_REF="${3:-HEAD}"
OUTPUT_DIR="${4:-$PROJECT_DIR}"
OUTPUT_FILE="$OUTPUT_DIR/review-package.md"

cd "$PROJECT_DIR"

# 自动检测 base_ref（如果未指定）
if [ -z "$BASE_REF" ]; then
    # 尝试获取最近一次提交的 parent
    BASE_REF=$(git rev-parse HEAD~1 2>/dev/null || echo "")
    if [ -z "$BASE_REF" ]; then
        # 初始提交，无 parent → 用空树
        BASE_REF="4b825dc642cb6eb9a060e54bf899d15f3f93828c"
    fi
fi

echo "Generating review package: $BASE_REF..$HEAD_REF"

# 1. Commit list
COMMIT_LIST=$(git log --oneline "$BASE_REF..$HEAD_REF" 2>/dev/null || echo "(initial commit)")

# 2. Files changed summary
FILES_CHANGED=$(git diff --stat "$BASE_REF..$HEAD_REF" 2>/dev/null || echo "(initial commit)")

# 3. File list with status
FILE_STATUS=$(git diff --name-status "$BASE_REF..$HEAD_REF" 2>/dev/null || echo "")

# 4. Net diff (limit to 500 lines to prevent context explosion)
DIFF=$(git diff "$BASE_REF..$HEAD_REF" 2>/dev/null || echo "(no diff)")
DIFF_LINES=$(echo "$DIFF" | wc -l)
if [ "$DIFF_LINES" -gt 500 ]; then
    DIFF="$(echo "$DIFF" | head -500)
... [truncated: $DIFF_LINES lines total, showing first 500]"
fi

# 5. Generate output
cat > "$OUTPUT_FILE" << REVIEW_EOF
# Review Package

> Auto-generated by gen-review-package.sh at $(date '+%Y-%m-%d %H:%M:%S')
> Base: $BASE_REF → Head: $HEAD_REF

---

## Commit List

\`\`\`
$COMMIT_LIST
\`\`\`

---

## Files Changed

\`\`\`
$FILES_CHANGED
\`\`\`

---

## File Status

| Status | File |
|--------|------|
$(echo "$FILE_STATUS" | awk '{print "| " $1 " | " $2 " |"}')

---

## Net Diff

\`\`\`diff
$DIFF
\`\`\`

---

## Review Checklist (for tester)

- [ ] **Spec Compliance**: Does the diff implement exactly what the task requires, no more and no less?
- [ ] **Code Quality**: Are there any quality risks (error handling, edge cases, naming)?
- [ ] **Evidence**: Paste specific code snippets from the diff as evidence for your verdict.

**VERDICT: PASS / FAIL**
REVIEW_EOF

echo "Review package written to: $OUTPUT_FILE"
echo "Lines: $DIFF_LINES"
